name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true
          cache-version: ${{ hashFiles('**/Gemfile.lock') }}
      - name: Run tests
        run: |
          bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml
      - name: Rspec Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: rspec.xml